### PR TITLE
zip downloading

### LINKED ISSUE #33: Installing from git
`npm` can install packages directly from `git` (see https://linux.how2shout.com/how-to-install-a-npm-package-directly-from-github/).

For example we can install the private repo I modified for this test with:

`npm install git@github.com:razcore-rad/godot-colorpicker-presets.git[#branch/tag/commit]`

And the public repo with:

`https://github.com/razcore-rad/godot-colorpicker-presets.git[#branch/tag/commit]`

Where the `#branch`, `#tag`, `#commit` specification is optional.

For example:

```nu
code/razcore-rad/godot-4-dbg via 🐍 v3.11.2 (default) 
❯ npm i git@github.com:razcore-rad/godot-colorpicker-presets.git#npm-test

added 1 package in 4s

code/razcore-rad/godot-4-dbg via  v20.1.0 via 🐍 v3.11.2 (default) 
❯ ls node_modules/@razcore-rad/colorpicker_presets/
╭───┬──────────────────────────────────────────────────────────────────────┬──────┬────────┬───────────────╮
│ # │                                 name                                 │ type │  size  │   modified    │
├───┼──────────────────────────────────────────────────────────────────────┼──────┼────────┼───────────────┤
│ 0 │ node_modules/@razcore-rad/colorpicker_presets/LICENSE                │ file │ 1.1 KB │ 5 minutes ago │
│ 1 │ node_modules/@razcore-rad/colorpicker_presets/README.md              │ file │ 1.4 KB │ 5 minutes ago │
│ 2 │ node_modules/@razcore-rad/colorpicker_presets/addons                 │ dir  │ 4.1 KB │ 5 minutes ago │
│ 3 │ node_modules/@razcore-rad/colorpicker_presets/colorpicker_presets.gd │ file │  722 B │ 5 minutes ago │
│ 4 │ node_modules/@razcore-rad/colorpicker_presets/package.json           │ file │  669 B │ 5 minutes ago │
│ 5 │ node_modules/@razcore-rad/colorpicker_presets/plugin.cfg             │ file │  238 B │ 5 minutes ago │
│ 6 │ node_modules/@razcore-rad/colorpicker_presets/presets.hex            │ file │  288 B │ 5 minutes ago │
│ 7 │ node_modules/@razcore-rad/colorpicker_presets/project.godot          │ file │  408 B │ 5 minutes ago │
│ 8 │ node_modules/@razcore-rad/colorpicker_presets/readme                 │ dir  │ 4.1 KB │ 5 minutes ago │
╰───┴──────────────────────────────────────────────────────────────────────┴──────┴────────┴───────────────╯

code/razcore-rad/godot-4-dbg via  v20.1.0 via 🐍 v3.11.2 (default) 
❯ bat package.json
         File: package.json
     1   {
     2     "dependencies": {
     3       "@razcore-rad/colorpicker_presets": "github:razcore-rad/godot-colorpicker-presets#npm-test"
     4     }
     5   }
```

This is a feature request for `gpm` so we can use:

```nu
code/razcore-rad/godot-4-dbg via  v20.1.0 via 🐍 v3.11.2 (default) took 2s 
❯ bat godot.package
         File: godot.package
     1   packages: {
     2       @bendn/remap: 5.1.0,
     3       git@github.com:razcore-rad/godot-colorpicker-presets.git: npm-test
     4   }
```
Right now I'm getting this error if I run `gpm update` with the above `godot.package` file:

```nu
code/razcore-rad/godot-4-dbg via  v20.1.0 via 🐍 v3.11.2 (default) took 20s 
❯ gpm update
       Error called `Result::unwrap()` on an `Err` value: missing field `dist` at line 1 column 21 (@src/config_file.rs:63)
```

I also tried:

```nu
code/razcore-rad/godot-4-dbg via  v20.1.0 via 🐍 v3.11.2 (default) 
❯ bat godot.package
         File: godot.package
     1   packages: {
     2       @bendn/remap: 5.1.0,
     3       @razcore-rad/colorpicker_presets: github:razcore-rad/godot-colorpicker-presets#npm-test
     4   }

code/razcore-rad/godot-4-dbg via  v20.1.0 via 🐍 v3.11.2 (default) took 27s 
❯ gpm update
       Error called `Result::unwrap()` on an `Err` value: missing field `dist` at line 1 column 3656 (@src/config_file.rs:63)
```

### PR DESCRIPTION
**Pull request by bend-n**
implements #33

### CODE REVIEW

**Comment by razcore-rad** [comment]
Thanks for looking into this!

**Comment by razcore-rad** [comment]
Quick question: this only works with tarballs/zips etc? But not repos like `https://github.com/bend-n/splitter.git` with version like `main/branch/tag`, correct?

So for example something like:

```
packages: {
  "https://github.com/bend-n/splitter.git": main
}
```

Or is there a specific syntax that works this way? I checked the `godot.package` file from the commit.

**Comment by bend-n** [comment]
this pr doesnt add `.git`, correct.
if you want to specify the branch or something you can do `https://github.com/bend-n/splitter/archive/refs/heads/ref.zip`.

**Comment by razcore-rad** [comment]
That's what I thought, thanks!

**Pull request merged**
